### ISSUE TITLE
 ${img_directory}    -video ${path to video}

### ISSUE THREAD

**Issue by henbucuoshanghai** [Amanbhandula/AlphaPose#3]
${img_directory}      in the code of demo.py,change it to my own directoryof imgs,but has wrong

**Comment by henbucuoshanghai** [comment]
File "anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/jit/frontend.py", line 422, in build_Subscript
    raise NotSupportedError(base.range(), "slicing multiple dimensions at the same time isn't supported yet")
torch.jit.frontend.NotSupportedError: slicing multiple dimensions at the same time isn't supported yet
        proposals (Tensor): boxes to be encoded
    """

    # perform some unpacking to make it JIT-fusion friendly
    wx = weights[0]
    wy = weights[1]
    ww = weights[2]
    wh = weights[3]

    proposals_x1 = proposals[:, 0].unsqueeze(1)
                   ~~~~~~~~~ <--- HERE
    proposals_y1 = proposals[:, 1].unsqueeze(1)
    proposals_x2 = proposals[:, 2].unsqueeze(1)
    proposals_y2 = proposals[:, 3].unsqueeze(1)

    reference_boxes_x1 = reference_boxes[:, 0].unsqueeze(1)
    reference_boxes_y1 = reference_boxes[:, 1].unsqueeze(1)
    reference_boxes_x2 = reference_boxes[:, 2].unsqueeze(1)
    reference_boxes_y2 = reference_boxes[:, 3].unsqueeze(1)

**Comment by henbucuoshanghai** [comment]
why??????????

**Comment by Lyndsey-Xing** [comment]
hello
I also have the same problem, how can I solve it?

**Comment by ABDULMAWLA** [comment]
i solved this problem 
uninstall torch=0.4.1

**Comment by ABDULMAWLA** [comment]
i solved it 
just uninstall trorch==0.4.1
